# --- active training options ---
case_study: 'four_branch_6' # Specify target LS: four_branch_6, himmelblau, pushover_frame, le_frame, hat, damped_oscillator, rp55
al_strategy: 'u'    #knee, compromised, eff, u, corr_det, corr_eigen, corr_entropy, corr_condvar, random
al_batch: 1   # batch sample size per active iteration
budget: 200   # max number of samples
doe: 10     # initial DoE with LHS
n_mcs_pool: 1000000  # size of MonteCarlo pool candidates
seed: -1 # -1 for random seed (default)

# --- reliability estimation---
n_mcs_pf: 10000000 # size of MonteCarlo sampling for pf estimation

#--- output model----
save_interval: 10
pareto_metrics: False