# --- active training options ---
case_study: 'hat' # Specify target LS: four_branch_6, himmelblau, pushover_frame, le_frame, hat, damped_oscillator, rp55
al_strategy: 'mo_reliability'    #knee, compromised, eff, u, corr_det, corr_eigen, corr_entropy, corr_condvar, random
al_batch: 1   # batch sample size per active iteration
budget: 100   # max number of samples
doe: 10     # initial DoE with LHS
n_mcs_pool: 1000000  # size of MonteCarlo pool candidates
seed: null # null for random seed (default)

# --- MO reliability trade-off (gamm a) control ---
N_it: 2 # Number of iterations to consider for moving average
delta_p0: 0.2 # (0,1) threshold of relative difference at which gamma=0.5
k_balance: 40 # Positive constant controlling how quickly gamma transition from 0 to 1

# --- reliability estimation---
n_mcs_pf: 10000000 # size of MonteCarlo sampling for pf estimation

#--- output model----
save_interval: 25
pareto_metrics: True